server:
  port: 8080
com:
  zeeroiq:
    inventory-service-host: http://localhost:8081

spring:
  application:
    name: beer-service
  # Spring Data hangs when not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  # ehcache config properties
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  # active mq configuration default username and password
  artemis:
    user: artemis
    password: simetraehcapa


logging:
  level:
    com:
      shri: debug