server:
  port: 8080
com:
  zeeroiq:
    inventory-service-host: http://localhost:8081
# ehcache config properties
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
# active mq configuration default username and password
  artemis:
    user: artemis
    password: simetraehcapa

logging:
  level:
    com:
      shri: debug