server:
  port: 8080
com:
  zeeroiq:
    inventory-service-host: http://localhost:8081
# ehcache config properties
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
